
### POST request to create a new Patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "asif billing",
  "email": "test_billing70_account@azw.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}
